### ISSUE TITLE
Events/GameEvents... LuaEvents?

### ISSUE THREAD

**Issue by kyle-mcknight-accesso** [Sukritact/Civilization-VI-Modding-Knowledge-Base#4]
This guide has "Events" and "GameEvents" as tables for with event emitters to listen to. But the only working ones I've found are using "LuaEvents". I'm quite confused. Even the ModBuddy sample project isn't very complete. Where can I find more info about this?

**Comment by kyle-mcknight** [comment]
Never mind. It's simple enough to do a regex search through Civ 6's Assets folder to get a lot of the event's to be listened to.

For anyone that wants it just search for `events\.add` case-insensitive regexp in the civ 6 `Base\Assets\*` folder/files
